name: MelodyMint - Production Workflow

on:
  push:
    branches: [production]

jobs:
  build:
    runs-on: production

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Create and activate virtual environment
        run: |
          python3 -m venv .venv
          source .venv/bin/activate

      - name: Install dependencies
        run: |
          source .venv/bin/activate
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create .env file
        run: |
          echo "DB_USERNAME=${{ secrets.DB_NAME }}" > .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_URL }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_USERNAME }}" >> .env
          echo "DB_PASSWORD=${{ secrets.JWT_ALGORITHM }}" >> .env
          echo "DB_PASSWORD=${{ secrets.JWT_SECRET }}" >> .env
