name: MelodyMint - Production Workflow

on:
  push:
    branches: [production]

jobs:
  build:
    runs-on: production

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Create and activate virtual environment
        run: |
          python3 -m venv .venv
          source .venv/bin/activate

      - name: Install dependencies
        run: |
          sudo apt-get install portaudio19-dev -y
          source .venv/bin/activate
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt

      - name: Create .env file
        run: |
          echo "APP_NAME=${{ secrets.APP_NAME }}" > .env
          echo "FRONTEND_APP_DOMAIN=${{ secrets.FRONTEND_APP_DOMAIN }}" >> .env
          echo "FRONTEND_APP_URI=${{ secrets.FRONTEND_APP_URI }}" >> .env
          echo "APP_ORGINS=${{ secrets.APP_ORGINS }}" >> .env
          echo "APP_SECRET_KEY=${{ secrets.APP_SECRET_KEY }}" >> .env
          echo "SUPPORTED_BLOCKCHAINS=${{ secrets.SUPPORTED_BLOCKCHAINS }}" >> .env
          echo "DB_URL=${{ secrets.DB_URL }}" >> .env
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "DB_APP_NAME=${{ secrets.DB_APP_NAME }}" >> .env
          echo "JWT_SECRET_ACCESS=${{ secrets.JWT_SECRET_ACCESS }}" > .env
          echo "JWT_EXPIRY_MINUTES_ACCESS=${{ secrets.JWT_EXPIRY_MINUTES_ACCESS }}" >> .env
          echo "JWT_SECRET_REFRESH=${{ secrets.JWT_SECRET_REFRESH }}" >> .env
          echo "JWT_EXPIRY_MINUTES_REFRESH=${{ secrets.JWT_EXPIRY_MINUTES_REFRESH }}" >> .env
          echo "JWT_REFRESH_COOKIE_NAME=${{ secrets.JWT_REFRESH_COOKIE_NAME }}" >> .env
          echo "ALCHEMY_SECRET_KEY=${{ secrets.ALCHEMY_SECRET_KEY }}" >> .env
          echo "PINATA_API_KEY=${{ secrets.PINATA_API_KEY }}" >> .env
          echo "PINATA_SECRET_KEY=${{ secrets.PINATA_SECRET_KEY }}" >> .env
          echo "PINATA_JWT_TOKEN=${{ secrets.PINATA_JWT_TOKEN }}" >> .env
          echo "PINATA_URI=${{ secrets.PINATA_URI }}" >> .env
          echo "PINATA_IPFS_URI=${{ secrets.PINATA_IPFS_URI }}" >> .env
          echo "MELODY_MINT_CONTRACT_ADDRESS=${{ secrets.MELODY_MINT_CONTRACT_ADDRESS }}" > .env

      - name: Run Update Services
        run: |
          sleep 5
          sudo systemctl stop melodymint_backend.service
          sudo cp melodymint_backend.service /etc/systemd/system/
          sudo systemctl daemon-reload
          sudo systemctl enable melodymint_backend.service
          sudo systemctl start melodymint_backend.service
